<?php
/*
  $Id: conditions.php,v 1.22 2003/06/05 23:26:22 hpdl Exp $

  osCommerce, Open Source E-Commerce Solutions
  http://www.oscommerce.com

  Copyright (c) 2003 osCommerce

  Released under the GNU General Public License
*/

  require('includes/application_top.php');

  require(DIR_WS_LANGUAGES . $language . '/' . FILENAME_CONDITIONS);

  $breadcrumb->add(NAVBAR_TITLE, tep_href_link(FILENAME_CONDITIONS));
?>
<!doctype html public "-//W3C//DTD HTML 4.01 Transitional//EN">
<html <?php echo HTML_PARAMS; ?>>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=<?php echo CHARSET; ?>">
<title><?php echo TITLE; ?></title>
<base href="<?php echo (($request_type == 'SSL') ? HTTPS_SERVER : HTTP_SERVER) . DIR_WS_CATALOG; ?>">
<link rel="stylesheet" type="text/css" href="stylesheet.css">
</head>
<body marginwidth="0" marginheight="0" topmargin="0" bottommargin="0" leftmargin="0" rightmargin="0">
<!-- header //-->
<?php require(DIR_WS_INCLUDES . 'header.php'); ?>
<!-- header_eof //-->

<!-- body //-->
<table border="0" width="779" cellspacing="3" cellpadding="0" class="maintable" align="center">
  <tr>
    <td width="<?php echo BOX_WIDTH; ?>" valign="top"><table border="0" width="<?php echo BOX_WIDTH; ?>" cellspacing="0" cellpadding="2">
<!-- left_navigation //-->
<?php require(DIR_WS_INCLUDES . 'column_left.php'); ?>
<!-- left_navigation_eof //-->
    </table></td>
<!-- body_text //-->
    <td width="100%" valign="top"><table border="0" width="100%" cellspacing="0" cellpadding="0">
      <tr>
        <td><table border="0" width="100%" cellspacing="0" cellpadding="0">
          <tr>
            <td class="pageHeading"><?php echo HEADING_TITLE; ?></td>
            <td class="pageHeading" align="right"><?php echo tep_image(DIR_WS_IMAGES . 'table_background_specials.gif', HEADING_TITLE, HEADING_IMAGE_WIDTH, HEADING_IMAGE_HEIGHT); ?></td>
          </tr>
        </table></td>
      </tr>
      <tr>
        <td><?php echo tep_draw_separator('pixel_trans.gif', '100%', '10'); ?></td>
      </tr>
      <tr>
        <td class="main"><p>READ CAREFULLY. This Terms of Use Agreement ( &quot;Terms of Use&quot; ) applies to use of the Performanceauto.us website located at http://www.performanceauto.us (the &quot;Site&quot; ). The Site is the property of Performanceauto.us (“Performanceauto.us”). Before you make any purchases, you must first establish a customer account ( &quot;My Account&quot; ). BY CLICKING &quot;I HAVE READ, UNDERSTAND AND AGREE TO THE TERMS OF USE,&quot; YOU AGREE TO THESE TERMS OF USE. IF YOU DO NOT AGREE, DO NOT CLICK ON THE BUTTON AND DO NOT USE THE SITE. </p>
          <p>Performanceauto.us reserves the right, at its sole discretion, to change, add or remove portions of this Terms of Use, at any time. It is your responsibility to check this Terms of Use each time before using the Site. Your continued use of the Site following the posting of changes will mean that you accept and agree to the changes. <strong>You agree that all subsequent purchases by you will be subject to the terms and conditions of this Terms of Use, which shall apply until we post a modified Terms of Use and then in accordance with such modified Terms of Use. </strong>As long as you comply with this Terms of Use and any such modifications, Performanceauto.us grants you ( &quot;End User&quot; ) a personal, non-exclusive, non-transferable, non-sublicensable, limited privilege to enter and use the Site. </p>
          <p>1. Content; Copyright and Trademark Notice. All media (downloaded or samples), software, text, images, graphics, user interfaces, music, videos, photographs, trademarks, logos, artwork and other content on the Site (collectively, &quot;Content&quot; ), including but not limited to the design, selection, arrangement, and coordination of such Content on the Site is owned or licensed by or to Performanceauto.us, and is protected by copyright, trade dress, and trademark laws, and various other intellectual property rights laws. Except as expressly provided in this Terms of Use, no part of the Site and no Content may be reproduced, recorded, retransmitted, sold, rented, broadcast, distributed, published, uploaded, posted, publicly displayed, altered to make new works, performed, digitized, compiled, translated or transmitted in any way to any other computer, website or other medium or for any commercial purpose, without Performanceauto.us's prior express written consent. Except as expressly provided herein, you are not granted any rights or license to patents, copyrights, trade secrets, trade dress, rights of publicity or trademarks with respect to any of the Content, and Performanceauto.us reserves all rights not expressly granted hereunder. Performanceauto.us expressly disclaims all responsibility and liability for uses by you of any Content obtained on or in connection with the Site. </p>
          <p>2. Registration; Customer Accounts; Use of Site. Certain services offered on or through the Site require you to first open a My Account. You are responsible for maintaining the confidentiality of your My Account information, including your password, and for all activity that occurs under your account. You agree to notify Performanceauto.us immediately of any unauthorized use of your account or password, or any other breach of security. You may be held liable for losses incurred by Performanceauto.us or any other user of the Site due to someone else using your password or customer account. You may not use anyone else's password or customer account at any time. You may not attempt to gain unauthorized access to the Site. Should you attempt to do so, assist others in making such attempts, or distributing instructions, software or tools for that purpose, then your customer My Account will be terminated. You agree to provide us with accurate, current and complete information about yourself and your billing information as prompted by the registration process. You may update any of your My Account information, designate a different credit card to be billed, or change the applicable expiration date on your currently designated credit card, by clicking on the My Account button and selecting the appropriate link. You may not use any automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy, probe, test or monitor any portion of the Site or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the Site or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Site. You agree that you will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Site or any of the systems or networks comprising or connected to the Site. </p>
          <p>You also agree that Performanceauto.us may, in its sole discretion and without prior notice to you, terminate your access to the Site and your My Account for any reason, including without limitation: (1) attempts to gain unauthorized access to the Site or assistance to others' attempting to do so, (2) overcoming software security features limiting use of or protecting any Content, (3) discontinuance or material modification of the Site or any service offered on or through the Site, (4) violations of this Terms of Use, (5) failure to pay for purchases, (6) suspected or actual copyright infringement, (7) unexpected operational difficulties, or (8) requests by law enforcement or other government agencies. You agree that Performanceauto.us will not be liable to you or to any third party for termination of your access to the Site. </p>
          <p>3. Consent To Collection, Use &amp; Disclosure of Your Personal Information. As more fully described in our Privacy Policy, (click here to view), you must disclose certain Personally Identifiable Information to use our Site, register, and make purchases. As a condition of registering with our Site or making any purchases of any products and/or services or conduct any transactions, you represent that you have first read our Privacy Policy and consent to the collection, use and disclosure of your Personally Identifiable Information and Non-Personally Identifiable Information as described in our Privacy Policy. Our Privacy Policy's terms and conditions will change from time to time, and as a condition of browsing the Site, using any features or making any purchase, you agree that you will first review our Privacy Policy prior to making any initial or subsequent purchases. </p>
          <p>While Performanceauto.us takes reasonable steps to safeguard and to prevent unauthorized access to your personal information, we cannot be responsible for the acts of those who gain unauthorized access, and we make no warranty, express, implied, or otherwise, that we will prevent unauthorized access to your private information. IN NO EVENT SHALL PERFORMANCEAUTO.US OR ITS AFFILIATES BE LIABLE FOR ANY DAMAGES (WHETHER CONSEQUENTIAL, DIRECT, INCIDENTAL, INDIRECT, PUNITIVE, SPECIAL OR OTHERWISE) ARISING OUT OF, OR IN ANY WAY CONNECTED WITH, A THIRD PARTY'S UNAUTHORIZED ACCESS TO YOUR PERSONAL INFORMATION, REGARDLESS OF WHETHER SUCH DAMAGES ARE BASED ON CONTRACT, STRICT LIABILITY, TORT OR OTHER THEORIES OF LIABILITY, AND ALSO REGARDLESS OF WHETHER PERFORMANCEAUTO.US WAS GIVEN ACTUAL OR CONSTRUCTIVE NOTICE THAT DAMAGES WERE POSSIBLE. </p>
          <p>4. Consent To Our Communication With You By E-Mail. By establishing a My Account with us, and each time you make a purchase through our Site, you grant permission for Performanceauto.us to contact you at your e-mail address regarding your purchase or information pertaining to your order. </p>
          <p>5. Conditions of Sale and Payment Terms. To purchase any goods and/or services on Performanceauto.us, you must (a) be at least eighteen (18) years of age or the applicable state age of majority, (b) be a natural person (no corporations, partnerships or other legal entities), and (c) be a resident in the 50 states of the United States of America, exclusive of its commonwealths, territories and possessions ( &quot;United States&quot; ). Prior to the purchase of any goods or services on our Site, you must provide us with a valid credit card number and associated payment information including all of the following: (i) your name as it appears on the card, (ii) your credit card number, (iii) the credit card type, (iv) the date of expiration and (v) any activation numbers or codes needed to charge your card. By submitting that information to us, you hereby agree that you authorize us to charge your card at our convenience but within thirty (30) days of credit card authorization. All sales of products and services are final. All charges from those sales are non refundable. </p>
          <p>6. Methods of Payment, Credit Card Terms and Taxes. All payments must be made by VISA, Master Card, or DISCOVER We currently do not accept cash, checks or any other payment form, although in the future we may change this policy. Your card issuer agreement governs your use of your designated card, and you must refer to that agreement and not this Terms of Use to determine your rights and liabilities as a cardholder. YOU, AND NOT Performanceauto.us, ARE RESPONSIBLE FOR PAYING ANY UNAUTHORIZED AMOUNTS BILLED TO YOUR CREDIT CARD BY A THIRD PARTY. You agree to pay all fees and charges incurred in connection with your purchases (including any applicable taxes) at the rates in effect when the charges were incurred. Unless you notify Performanceauto.us of any discrepancies within sixty (60) days after they first appear on your credit card statement, you agree that they will be deemed accepted by you for all purposes. If Performanceauto.us does not receive payment from your credit card issuer or its agent, you agree to pay all amounts due upon demand by Performanceauto.us or its agents. You are responsible for paying any governmental taxes imposed on your purchases, including, but not limited to, sales, use or value-added taxes. Performanceauto.us shall automatically charge and withhold the applicable sales tax for orders to be delivered to addresses within Minnesota and any other states or localities that it deems is required. </p>
          <p>7. Order Acceptance Policy. Your receipt of an electronic or other form of order confirmation does not signify our acceptance of your order, nor does it constitute confirmation of our offer to sell. Performanceauto.us reserves the right at any time after receipt of your order to accept or decline your order for any reason. Performanceauto.us further reserves the right any time after receipt of your order, without prior notice to you, to supply less than the quantity you ordered of any item. Your order will be deemed accepted by Performanceauto.us upon our delivery of products or services that you have ordered as indicated by our servers. All orders placed over $1000.00 ( U.S. ) must obtain pre-approval with an acceptable method of payment, as established by our credit and fraud avoidance department. We may require additional verifications or information before accepting any order. Performanceauto.us is a reseller to end users and does not accept orders from resellers, exporters, wholesalers, any businesses of any kind or other customers who intend to resell. </p>
          <p>8. No Responsibility To Sell Mispriced Products Or Services. Performanceauto.us shall have the right to refuse or cancel any orders placed for products and/or services listed at an incorrect price, rebate or refund, or containing any other incorrect information or typographical errors. Performanceauto.us shall have the right to refuse or cancel any such orders whether or not the order has been confirmed and your credit card charged. If your credit card has already been charged for the purchase and your order is canceled, Performanceauto.us shall immediately issue a credit to your credit card account in the amount of the charge. </p>
          <p>9. Modifications to Prices or Billing Terms. PERFORMANCEAUTO.US RESERVES THE RIGHT, AT ANY TIME, TO CHANGE ITS PRICES AND BILLING METHODS FOR PRODUCTS OR SERVICES SOLD, EFFECTIVE IMMEDIATELY UPON POSTING ON THE SITE OR BY E-MAIL DELIVERY TO YOU. </p>
          <p>10. Price Comparisons, &quot;List Price&quot; and &quot;You Save&quot;. Price comparisons may be made throughout the site to indicate the relative savings amounts of our pricing. &quot;MSRP&quot; is the manufacturers' suggested retail price provided to us by our suppliers. We make no representation that a substantial number of these products have been sold or offered for sale at the list price. Actual retail prices in your area may be substantially different. Because we sell our merchandise over the internet on a national basis, it is not possible to know if our merchandise is sold at list price in any particular location or at any particular time. </p>
          <p>11. Service and Support for Goods Sold. All requests for technical service and support should be made directly to the manufacturer in accordance with their terms and conditions. </p>
          <p>12. Indemnification. You agree to indemnify and hold harmless Performanceauto.us and its parents, sister companies, subsidiaries, affiliates, service providers, other End Users, distributors, licensors, officers, directors and employees from any claim or demand, including reasonable attorneys' fees, made by any third party arising out of or related to your violation of this Terms of Use, or your violation of any law, regulation or third-party right. </p>
          <p>13. Disclaimer of Warranties. THE SITE, PRODUCTS, SERVICES, CONTENT, SOFTWARE, ARTWORK, DATA, AND INFORMATION ARE PROVIDED &quot;AS IS.&quot; ALL OF Performanceauto.us'S PHYSICAL PRODUCTS ARE GUARANTEED AGAINST MATERIAL DEFECTS FOR THIRTY (30) DAYS FROM THE DATE OF INVOICE. EXCEPT AS EXPRESSLY STATED HEREIN, PERFORMANCEAUTO.US EXPRESSLY DISCLAIMS ALL WARRANTIES AND/OR CONDITIONS, EXPRESS OR IMPLIED, AS TO ANY MATTER WHATSOEVER RELATING TO OR REFERENCED BY THE PERFORMANCEAUTO.US SITE, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES AND/OR CONDITIONS OF MERCHANTABILITY OR QUALITY OF DATA AND FITNESS FOR A PARTICULAR PURPOSE, SUITABILITY, TITLE, NON-INFRINGEMENT, LACK OF VIRUSES OR CORRESPONDENCE TO DESCRIPTION. </p>
          <p>14. LIMITATION OF LIABILITY. THE ENTIRE RISK ARISING OUT OF THE USE OF THE SITE, THE USE OF ANY PRODUCTS AND/OR SERVICES OFFERED ON OR IN CONNECTION WITH THE SITE, AND/OR THE USE OF ANY CONTENT REMAINS WITH YOU. IN NO EVENT SHALL PERFORMANCEAUTO.US OR ITS LICENSORS OR ANY OF THEIR OFFICERS, DIRECTORS, EMPLOYEES, AGENTS OR AFFILIATES BE LIABLE FOR ANY CONSEQUENTIAL, INCIDENTAL, DIRECT, INDIRECT, SPECIAL, PUNITIVE, OR OTHER DAMAGES WHATSOEVER (INCLUDING, WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS INTERRUPTION, LOSS OF BUSINESS INFORMATION, OR OTHER PECUNIARY LOSS) ARISING OUT OF THIS TERMS OF USE OR THE USE OF OR INABILITY TO USE ANY PRODUCTS, SERVICES, AND/OR CONTENT, WITH THE DELAY OR INABILITY TO USE THE PERFORMANCEAUTO.US SITE OR RELATED SERVICES, THE PROVISION OF OR FAILURE TO PROVIDE PRODUCTS OR SERVICES, OR FOR ANY INFORMATION, SOFTWARE, PRODUCTS, SERVICES AND CONTENT OBTAINED THROUGH THE SITE, OR OTHERWISE ARISING OUT OF THE USE OF THE PERFORMANCEAUTO.US SITE WHETHER BASED ON CONTRACT, TORT, NEGLIGENCE, STRICT LIABILITY OR OTHERWISE EVEN IF PERFORMANCEAUTO.US HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. NOTWITHSTANDING ANYTHING ELSE IN THIS TERMS OF USE OR POSTED ON THE SITE, THE MAXIMUM LIABILITY THAT PERFORMANCEAUTO.US SHALL HAVE IS LIMITED TO ANY AMOUNTS ACTUALLY PAID TO PERFORMANCEAUTO.US BY END USER. YOU ASSUME ALL RISK OF LOSS FOR SHIPPED PRODUCTS. ORDER INFORMATION SUCH AS BILLING OR SHIPPING ADDRESS THAT IS INACCURATE OR INCOMPLETE MAY RESULT IN DELAYS THAT SHALL NOT BE THE RESPONSIBILITY OF Performanceauto.us. YOU ACKNOWLEDGE AND AGREE THAT THE LIMITATIONS OF LIABILITY, DISCLAIMERS OF WARRANTIES AND LIMITED REMEDIES SET FORTH HEREIN REPRESENT AN INSEPARABLE ALLOCATION OF RISK (INCLUDING, WITHOUT LIMITATION, IN THE EVENT OF A TOTAL AND FUNDAMENTAL BREACH OF THIS TERMS OF USE) THAT IS AN ESSENTIAL BASIS OF THE BARGAIN BETWEEN THE PARTIES. </p>
          <p>15. Policy to Terminate Privileges for Copyright Infringement. Pursuant to 17 U.S.C. &sect; 512 as amended by Title II of the Digital Millennium Copyright Act (the &quot;Act&quot;), Performanceauto.us will terminate the account of any customer, or vendor who uses his or her privileges to unlawfully transmit copyrighted material without a license, valid defense or fair use privilege to do so. After proper notification by the copyright holder or its agent to Performanceauto.us and later confirmation through court order or an admission by the customer that an account has been an instrument of unlawful infringement, Performanceauto.us will terminate the infringing customer's account. Performanceauto.us may also in its sole discretion decide to terminate a customer's account privileges prior to that time if it has good belief that infringement has in fact occurred. In addition, pursuant to 17 U.S.C. &sect; 512(c), Performanceauto.us has implemented procedures for receiving written notification of claimed infringements and for processing such claims in accordance with the Act. Performanceauto.us respects the intellectual property of others and we ask other to do the same. If you believe that your copyright has been infringed through the Performanceauto.us website, please contact &quot;Legal Department&quot;, via facsimile at (651) 905-3954, or mail at: Attn: Legal Department, Performanceauto.us, 1520 Oakbrooke Lane, Eagan, MN 55122. </p>
          <p>Any written notice describing the infringing activity must include the following information: </p>
          <p>•&nbsp; An electronic or physical signature of the person authorized to act on behalf of the owner of an exclusive that is allegedly infringed; </p>
          <p>•&nbsp; A description of the allegedly infringing work or material; </p>
          <p>•&nbsp; A description of where the allegedly infringing material is located on the site; </p>
          <p>•&nbsp; Information reasonably sufficient to allow us to contact you, such as your address, telephone number and e-mail address; </p>
          <p>•&nbsp; A statement by you that you have a good faith belief that the disputed use of the material is not authorized by the copyright or other proprietary right owner, its agent, or the law; and </p>
          <p>•&nbsp; A statement by you that the above information and notification is accurate, and under penalty of perjury, that you are the copyright owner or authorized to act on behalf of the owner whose exclusive right is allegedly infringed. </p>
          <p>16. General. No delay or failure to take action under this Terms of Use shall constitute any waiver by Performanceauto.us of any provision of this Terms of Use. If any provision of this Terms of Use is invalid or unenforceable under applicable law, it is, to that extent, deemed enforceable to the fullest extent possible (and severable in the event such provision is completely unenforceable) and the remaining provisions of this Terms of Use will continue in full force and effect. This Terms of Use will bind and inure to the benefit of Performanceauto.us's permitted successors and assigns. Any claim under these Terms of Use must be brought within one (1) year after the cause of action arises. This Terms of Use shall be governed by the laws of the State of Minnesota without regard to or application of any conflict of laws provisions. You consent to the exclusive jurisdiction of the state and federal courts sitting in Hennepin County , in the State of Minnesota . This Terms of Use is personal to you and may not be transferred, assigned or delegated to anyone. Any attempt by you to assign, transfer or delegate this Terms of Use shall be null and void. Performanceauto.us may freely assign this Terms of Use without consent or notice. This Terms of Use (including all documents expressly incorporated herein by reference, including but not limited, to the relevant Usage Rules) constitutes the complete and exclusive agreement between Performanceauto.us and you with respect to the subject matter hereof and supersedes all prior oral or written understandings, communications or agreements not specifically incorporated herein. </p>
          <p>Last modified: July 7, 2004 </p>
          <p>&nbsp; </p></td>
      </tr>
      <tr>
        <td><?php echo tep_draw_separator('pixel_trans.gif', '100%', '10'); ?></td>
      </tr>
      <tr>
        <td><table border="0" width="100%" cellspacing="1" cellpadding="2" class="infoBox">
          <tr class="infoBoxContents">
            <td><table border="0" width="100%" cellspacing="0" cellpadding="2">
              <tr>
                <td width="10"><?php echo tep_draw_separator('pixel_trans.gif', '10', '1'); ?></td>
                <td align="right"><?php echo '<a href="' . tep_href_link(FILENAME_DEFAULT) . '">' . tep_image_button('button_continue.gif', IMAGE_BUTTON_CONTINUE) . '</a>'; ?></td>
                <td width="10"><?php echo tep_draw_separator('pixel_trans.gif', '10', '1'); ?></td>
              </tr>
            </table></td>
          </tr>
        </table></td>
      </tr>
    </table></td>
<!-- body_text_eof //-->
    <td width="<?php echo BOX_WIDTH; ?>" valign="top"><table border="0" width="<?php echo BOX_WIDTH; ?>" cellspacing="0" cellpadding="2">
<!-- right_navigation //-->
<?php require(DIR_WS_INCLUDES . 'column_right.php'); ?>
<!-- right_navigation_eof //-->
    </table></td>
  </tr>
</table>
<!-- body_eof //-->

<!-- footer //-->
<?php require(DIR_WS_INCLUDES . 'footer.php'); ?>
<!-- footer_eof //-->
<br>
</body>
</html>
<?php require(DIR_WS_INCLUDES . 'application_bottom.php'); ?>
